import { UserRole } from './auth.interface';

export const PERMISSIONS = {
  // User Management
  MANAGE_USERS_VIEW: 'MANAGE_USERS_VIEW',
  MANAGE_USERS_CREATE: 'MANAGE_USERS_CREATE',
  MANAGE_USERS_EDIT: 'MANAGE_USERS_EDIT',
  MANAGE_USERS_DELETE: 'MANAGE_USERS_DELETE',
  MANAGE_USERS_EDIT_ROLE: 'MANAGE_USERS_EDIT_ROLE', // Specific permission for changing roles

  // Product Management
  MANAGE_PRODUCTS_CREATE: 'MANAGE_PRODUCTS_CREATE',
  MANAGE_PRODUCTS_EDIT: 'MANAGE_PRODUCTS_EDIT',
  MANAGE_PRODUCTS_DELETE: 'MANAGE_PRODUCTS_DELETE',
  MANAGE_PRODUCTS_VIEW: 'MANAGE_PRODUCTS_VIEW',

  // Order Management
  MANAGE_ORDERS_VIEW: 'MANAGE_ORDERS_VIEW',
  MANAGE_ORDERS_EDIT_STATUS: 'MANAGE_ORDERS_EDIT_STATUS',

  // Settings Management
  MANAGE_SETTINGS_VIEW: 'MANAGE_SETTINGS_VIEW',
  MANAGE_SETTINGS_EDIT: 'MANAGE_SETTINGS_EDIT',

  // Dashboard
  VIEW_ADMIN_DASHBOARD: 'VIEW_ADMIN_DASHBOARD',
  VIEW_SELLER_DASHBOARD: 'VIEW_SELLER_DASHBOARD',

  // Profile Management
  MANAGE_OWN_PROFILE_VIEW: 'MANAGE_OWN_PROFILE_VIEW',
  MANAGE_OWN_PROFILE_EDIT: 'MANAGE_OWN_PROFILE_EDIT',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  superAdmin: [
    PERMISSIONS.MANAGE_USERS_VIEW,
    PERMISSIONS.MANAGE_USERS_CREATE,
    PERMISSIONS.MANAGE_USERS_EDIT,
    PERMISSIONS.MANAGE_USERS_DELETE,
    PERMISSIONS.MANAGE_USERS_EDIT_ROLE,
    PERMISSIONS.MANAGE_PRODUCTS_CREATE,
    PERMISSIONS.MANAGE_PRODUCTS_EDIT,
    PERMISSIONS.MANAGE_PRODUCTS_DELETE,
    PERMISSIONS.MANAGE_PRODUCTS_VIEW,
    PERMISSIONS.MANAGE_ORDERS_VIEW,
    PERMISSIONS.MANAGE_ORDERS_EDIT_STATUS,
    PERMISSIONS.MANAGE_SETTINGS_VIEW,
    PERMISSIONS.MANAGE_SETTINGS_EDIT,
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_OWN_PROFILE_VIEW,
    PERMISSIONS.MANAGE_OWN_PROFILE_EDIT,
  ],
  admin: [
    PERMISSIONS.MANAGE_USERS_VIEW,
    PERMISSIONS.MANAGE_USERS_CREATE,
    PERMISSIONS.MANAGE_USERS_EDIT,
    PERMISSIONS.MANAGE_PRODUCTS_CREATE,
    PERMISSIONS.MANAGE_PRODUCTS_EDIT,
    PERMISSIONS.MANAGE_PRODUCTS_VIEW,
    PERMISSIONS.MANAGE_ORDERS_VIEW,
    PERMISSIONS.MANAGE_ORDERS_EDIT_STATUS,
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_OWN_PROFILE_VIEW,
    PERMISSIONS.MANAGE_OWN_PROFILE_EDIT,
  ],
  seller: [
    PERMISSIONS.MANAGE_PRODUCTS_CREATE,
    PERMISSIONS.MANAGE_PRODUCTS_EDIT,
    PERMISSIONS.MANAGE_PRODUCTS_DELETE,
    PERMISSIONS.MANAGE_PRODUCTS_VIEW,
    PERMISSIONS.MANAGE_ORDERS_VIEW,
    PERMISSIONS.MANAGE_ORDERS_EDIT_STATUS,
    PERMISSIONS.VIEW_SELLER_DASHBOARD,
    PERMISSIONS.MANAGE_OWN_PROFILE_VIEW,
    PERMISSIONS.MANAGE_OWN_PROFILE_EDIT,
  ],
  customer: [
    PERMISSIONS.MANAGE_OWN_PROFILE_VIEW,
    PERMISSIONS.MANAGE_OWN_PROFILE_EDIT,
    PERMISSIONS.MANAGE_ORDERS_VIEW, // Customers can view their own orders
  ],
};
